### ISSUE TITLE
Lagging

### ISSUE THREAD

**Issue by NagaNecromancer** [AllTheMods/SLOP2-slice-of-pie-2#1]
Hello, i have experienced some performance issues, i've got a laptop with an AMD Ryzen 5 4000 series processor, and an 1650 Ti, and i can't seem to get more than 40 fps , even tough i capped it at 60, Vsync is turned off, and minimal settings

**Comment by coder2000** [comment]
I am having similar experiences, I load the game and it was lagging pretty bad. I had to minimize the graphics settings and increase the memory allocation to even get it usable. I can run vanilla with full settings.

**Comment by MadWomen** [comment]
lower your mipmap settings, that usually improves your fps.
