### ISSUE TITLE
JEI not displaying all items

### ISSUE THREAD

**Issue by 11lavey** [AllTheMods/SLOP2-slice-of-pie-2#14]
I am running version 2.2.0A
JEI is not displaying some of the items on the right side even when searching for them.  
I have tried messing around with the in-game setting of JEI and had no luck.
I installed JEI integration to see if that would fix but it did not 
![jei not working](https://user-images.githubusercontent.com/46272349/126847247-3e4243b5-61de-4bd2-b910-3e854ae64a94.PNG)
(I do believe that other items are being affected as well)

**Comment by lexxieblack** [comment]
It's now fixed in the dev version, will be released tomorrow.
Please let us know if there are any other items missing that were overlooked!
