### ISSUE TITLE
Recipes Missing Ingredients (Functional or otherwise)

### ISSUE THREAD

**Issue by lotherjem** [AllTheMods/SLOP2-slice-of-pie-2#17]
Listing some recipes that are either missing in jei and/or actual effect:
Certus quartz seeds = missing quartz in recipe, works anyway.
Glowing Bee = refuses food, recipe both errored and nonfunctional
Will add more if found.

**Comment by lexxieblack** [comment]
Thanks for the info.
As I looked into it, the Certus Quartz Seed recipe is added by AE2, there isn't a script or anything that removes an additional recipe. It also makes sense that the CQ seeds would need CQ.
For the Glowing Bee, I changed it to be 5 Glowstone Blocks. 
Please let me know if you find something else!
