### ISSUE TITLE
issue launching on mac

### ISSUE THREAD

**Issue by ldubya344** [AllTheMods/SLOP2-slice-of-pie-2#2]
Hi, I am unable to launch the game when using my MacBook Pro. 

It comes up with writing 27/27 and then disappears and fails to launch. I don't really know what I can do so solve this. I have tried uninstalling the program and the launcher and no difference. 

I seem to be unable to share crash logs as it isn't reporting any crashes.

**Comment by MadWomen** [comment]
you may have to manually delete minecraft from curse/twitch and then reinstall it.
