### ISSUE TITLE
Netherite bee cannot be bred

### ISSUE THREAD

**Issue by Giovanni-NL** [AllTheMods/SLOP2-slice-of-pie-2#21]
The netherite bee does not spawn in the wild, and can only be bred by mating two netherite bees. So I'm kinda stuck on getting those...

Can a recipe be added which allows the netherite bee to be bred?  I could imagine having a withered bee + diamond bee to be good parents for this puppy. Just a suggestion.

I'm using modpack version 2.2.2

**Comment by lexxieblack** [comment]
They don't spawn, nor are bred. The guide is in the wiki. They are mutated from Gold bees.

**Comment by Giovanni-NL** [comment]
Good to know. Thanks!

**Comment by lexxieblack** [comment]
Here's the link to it: https://miro.com/app/board/o9J_lXWb-uM=/
