### ISSUE TITLE
Request: Add elevator block as valid apiary block

### ISSUE THREAD

**Issue by Giovanni-NL** [AllTheMods/SLOP2-slice-of-pie-2#22]
Since elevator blocks are an ideal method of getting in and out of apiaries, without having the bees escape, I've looked into adding those blocks as valid apiary blocks.  I've tested this locally and seems to work like a charm.

Can you please consider updating \kubejs\server_scripts\RBees\valid_apiary.js by adding the following line to the whitelist: 

/elevatorid:.*/,

Modpack version 2.2.2 (but will probably also be interesting for the other AllTheMods packs)

**Comment by lexxieblack** [comment]
You will have Honey Glass in 2.2.3 which will let players walk through it, but I will add elevators to that list :)

**Comment by Giovanni-NL** [comment]
Honey glass sounds awesome. Anything to keep those puppies inside helps.

**Comment by lexxieblack** [comment]
For the next update we were able to remove the entire valid apiary file, all blocks now have it by default.
