### ISSUE TITLE
Server Pack Empty

### ISSUE THREAD

**Issue by alfaoz** [AllTheMods/SLOP2-slice-of-pie-2#25]
The server.zip of the mod is just an empty 4 kb file

**Comment by radiomike** [comment]
It's not. There should be 3 files.

**Comment by radiomike** [comment]
You can use https://github.com/AllTheMods/ATM-6/wiki/Installing-A-Server as a guide for installing.
If you need further assistance I'd recommend joining the discord. https://discordapp.com/invite/rbSZNDQ
