### ISSUE TITLE
Unmodified: 2.2.4 Server and Client files aren't synced.

### ISSUE THREAD

**Issue by Shadowthunder21** [AllTheMods/SLOP2-slice-of-pie-2#28]
Started a new Server for me and a few friends. and after over 3 hrs of testing and back and forth with Apex hosting, we found that the server and client files are matched/ synced properly and is causing a Failed to Sync registry data from server, closing connection.

**Comment by Westermin** [comment]
Most likely your client got updated while the server is still on the older version, easiest way to find out is checking the manifest.json file in the server, under "manifestType": "minecraftModpack" and then "version": "2.2.4" for the version number, check that the number is the same with the client.

**Comment by Shadowthunder21** [comment]
Nope! Just set up tonight. Downloaded everything 2.2.4 I can send screenshot of the conversation with Apex Hosting Support staff

**Comment by MadWomen** [comment]
currently there is a bug that curse isn't downloading or loading all the mods correctly, if you use a different launcher like GDL it will work fine, we're investigating this currently.

**Comment by MadWomen** [comment]
fixed in 2.2.4B
