### ISSUE TITLE
Mekanism Carboard Box crashes game

### ISSUE THREAD

**Issue by Yadokingu** [AllTheMods/SLOP2-slice-of-pie-2#3]
A Mekanism author says it has to be another mod breaking tag loading on client: https://github.com/mekanism/Mekanism/issues/6965
Crash Log: https://pastebin.com/RS9VP4YL

Edit: I tested the cardboard box in the full All the Mods 6 pack. There it doesn't crash the world and works as intended. Maybe that helps narrow down the problem?

**Comment by MadWomen** [comment]
i'll have a look on whats causing it, it seems to be some sort of blacklist issue.

**Comment by MadWomen** [comment]
found the issue with some old tweaks from a time where no claims were avaliable, since these tweaks are no longer needed, they are now removed in a dev build and will soon make its way in an update.

**Comment by Yadokingu** [comment]
Thank you. Is there any ETA on a new version of the pack, a way to get the dev build or a way to remove those tweaks myself? I now have a problem where my world crashes on load and from the error message it seems to be the same cause:

> The game crashed whilst rendering screen
> Error: java.lang.IllegalStateException: Tag drawerstooltip:compacting_drawers used before it was bound
> Exit Code: -1

**Comment by MadWomen** [comment]
thats a different issue all together but i'll have a look and see what i can figure out, there will be a pack update within the next few days.

**Comment by Yadokingu** [comment]
Are you sure? Seems like the same tag not bound thing with client tags being broken. But I guess I don't know that much about that stuff.
While restoring a world backup did nothing, deleting and reinstalling the pack (and then restoring the world backup) seems to have fixed the problem for now. I hope it doesn't come back.
But thanks for looking into it. :)

**Comment by MadWomen** [comment]
cardboard box issue fixed in version 2.1.1

**Comment by Yadokingu** [comment]
thank you!
