### ISSUE TITLE
Game keeps crashing (Error Log Added)

### ISSUE THREAD

**Issue by DanteAyagawe** [AllTheMods/SLOP2-slice-of-pie-2#6]
I have no idea why my game kept crashing down, but the moment I updated the ver of the modpack, it persisted on crashing, it never happened on the older ver, help ;-;

VVV
[crash-2021-03-03_09.54.21-server.txt](https://github.com/AllTheMods/SLOP2-slice-of-pie-2/files/6073124/crash-2021-03-03_09.54.21-server.txt)

**Comment by MadWomen** [comment]
remove optifine and try again.
