### ISSUE TITLE
All the Mods - Slice of Pi2 server wont even start with a fresh install?

### ISSUE THREAD

**Issue by kaancl3344** [AllTheMods/SLOP2-slice-of-pie-2#7]
I havent even touched the files but the server wont even start. I used the server downloader on the original site...
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 3/6/21 12:14 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.0.42.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.0.42.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.0.42.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.0.42.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:ResourceLocationMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- MOD resourcefulbees --
Details:
	Mod File: resourcefulbees-1.16.5-0.5.10b.jar
	Failure message: Resourceful Bees (resourcefulbees) has failed to load correctly
		net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: resourcefulbees:ıcy_bee
	Mod Version: 1.16.5-0.5.10b
	Mod Issue URL: https://github.com/Resourceful-Bees/ResourcefulBees/issues/new/choose
	Exception message: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: resourcefulbees:ıcy_bee
Stacktrace:
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:ResourceLocationMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:42) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:ResourceLocationMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.registries.DeferredRegister.register(DeferredRegister.java:114) ~[forge:?] {re:classloading}
	at com.resourcefulbees.resourcefulbees.registry.RegistryHandler.registerBee(RegistryHandler.java:151) ~[resourcefulbees:1.16.5-0.5.10b] {re:classloading}
	at com.resourcefulbees.resourcefulbees.registry.RegistryHandler.lambda$registerDynamicBees$1(RegistryHandler.java:81) ~[resourcefulbees:1.16.5-0.5.10b] {re:classloading}
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.Collections$UnmodifiableMap.forEach(Unknown Source) ~[?:1.8.0_271] {}
	at com.resourcefulbees.resourcefulbees.registry.RegistryHandler.registerDynamicBees(RegistryHandler.java:74) ~[resourcefulbees:1.16.5-0.5.10b] {re:classloading}
	at com.resourcefulbees.resourcefulbees.ResourcefulBees.<init>(ResourcefulBees.java:66) ~[resourcefulbees:1.16.5-0.5.10b] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.0] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_271] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1796398608 bytes (1713 MB) / 2138701824 bytes (2039 MB) up to 4187619328 bytes (3993 MB)
	CPUs: 12
	JVM Flags: 15 total; -XX:+AggressiveOpts -XX:ParallelGCThreads=4 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -Xmx4G -Xms2G
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.42.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.42.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.42.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.42.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.42.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.42
	FML Language Providers: 
		javafml@36.0
		minecraft@1
	Mod List: 
		rhino-1.7.13-build.14.jar                         |Rhino                         |rhino                         |1.7.13-build.14     |CREATE_REG|NOSIGNATURE
		ftb-essentials-1604.1.0.13.jar                    |FTB Essentials                |ftbessentials                 |1604.1.0.13         |CREATE_REG|NOSIGNATURE
		biggerreactors-1.16.4-0.4.3.jar                   |Bigger Reactors               |biggerreactors                |0.4.3               |CREATE_REG|NOSIGNATURE
		Cucumber-1.16.4-4.1.8.jar                         |Cucumber Library              |cucumber                      |4.1.8               |CREATE_REG|NOSIGNATURE
		pamhc2trees-1.16.3-1.0.0.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.0               |CREATE_REG|NOSIGNATURE
		woot-1.16.4-1.0.3.2.jar                           |Woot                          |woot                          |1.16.4-1.0.3.2      |CREATE_REG|NOSIGNATURE
		jei-1.16.4-7.6.1.71.jar                           |Just Enough Items             |jei                           |7.6.1.71            |CREATE_REG|NOSIGNATURE
		metalbarrels-3.3a.jar                             |Metal Barrels                 |metalbarrels                  |3.3a                |CREATE_REG|NOSIGNATURE
		AttributeFix-1.16.5-10.0.1.jar                    |AttributeFix                  |attributefix                  |10.0.1              |CREATE_REG|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Mekanism-1.16.5-10.0.21.448.jar                   |Mekanism                      |mekanism                      |10.0.21             |CREATE_REG|NOSIGNATURE
		bambooeverything-1.16.3-forge-1.0.0.jar           |Bamboo Everything             |bambooeverything              |1.16.3-forge-1.0.0  |CREATE_REG|NOSIGNATURE
		ae2extras-1.2-1.16.4.jar                          |AE2 Extras                    |ae2extras                     |1.2-1.16.4          |CREATE_REG|NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |CREATE_REG|NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |CREATE_REG|NOSIGNATURE
		Clumps-6.0.0.17.jar                               |Clumps                        |clumps                        |6.0.0.17            |CREATE_REG|NOSIGNATURE
		CookingForBlockheads_1.16.3-9.2.2.jar             |Cooking for Blockheads        |cookingforblockheads          |9.2.2               |CREATE_REG|NOSIGNATURE
		Placebo-1.16.4-4.4.1.jar                          |Placebo                       |placebo                       |4.4.1               |CREATE_REG|NOSIGNATURE
		dankstorage-3.14.jar                              |Dank Storage                  |dankstorage                   |3.14                |CREATE_REG|NOSIGNATURE
		appliedenergistics2-8.3.0-alpha.1.jar             |Applied Energistics 2         |appliedenergistics2           |8.3.0-alpha.1       |CREATE_REG|95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		[1.16.4]-additionalbars-1.6.0.jar                 |Additional Bars               |additionalbars                |1.6.0               |CREATE_REG|NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |CREATE_REG|NOSIGNATURE
		phosphophyllite-1.16.4-0.4.5.jar                  |Phosphophyllite               |phosphophyllite               |0.4.5               |CREATE_REG|NOSIGNATURE
		engineerstools-1.16.4-1.1.4.jar                   |Engineer's Tools              |engineerstools                |1.1.4               |CREATE_REG|bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		reliquary-1.16.3-1.3.4.1061.jar                   |Reliquary                     |xreliquary                    |1.16.3-1.3.4.1061   |CREATE_REG|NOSIGNATURE
		randompatches-2.4.4-forge.jar                     |RandomPatches                 |randompatches                 |2.4.4-forge         |CREATE_REG|92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		Morpheus-1.16.5-4.2.70.jar                        |Morpheus                      |morpheus                      |4.2.70              |CREATE_REG|NOSIGNATURE
		MekanismGenerators-1.16.5-10.0.21.448.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.21             |CREATE_REG|NOSIGNATURE
		forge-1.16.5-36.0.42-universal.jar                |Forge                         |forge                         |36.0.42             |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BloodMagic-1.16.4-3.1.0-15.jar                    |Blood Magic                   |bloodmagic                    |1.16.4-3.1.0-15     |CREATE_REG|NOSIGNATURE
		absentbydesign-1.16.5-1.4.1.jar                   |Absent By Design Mod          |absentbydesign                |1.16.5-1.4.1        |CREATE_REG|1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		MysticalAgriculture-1.16.4-4.1.5.jar              |Mystical Agriculture          |mysticalagriculture           |4.1.5               |CREATE_REG|NOSIGNATURE
		MysticalAgradditions-1.16.4-4.1.4.jar             |Mystical Agradditions         |mysticalagradditions          |4.1.4               |CREATE_REG|NOSIGNATURE
		alltheores-1.1.20-1.16.4-35.1.13.jar              |AllTheOres                    |alltheores                    |1.1.20-1.16.4-35.1.1|CREATE_REG|NOSIGNATURE
		chocolate-1.3.0-1.16.4.jar                        |Chocolate                     |chocolate                     |1.3.0-1.16.4        |CREATE_REG|NOSIGNATURE
		forge-1.16.5-36.0.42-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|NOSIGNATURE
		cofh_core-1.16.3-1.1.6.jar                        |CoFH Core                     |cofh_core                     |1.1.6               |CREATE_REG|NOSIGNATURE
		thermal_foundation-1.16.3-1.1.6.jar               |Thermal Series                |thermal                       |1.1.6               |CREATE_REG|NOSIGNATURE
		industrial-foregoing-1.16.5-3.2.10.1-decb7ae.jar  |Industrial Foregoing          |industrialforegoing           |3.2.10.1            |CREATE_REG|NOSIGNATURE
		useful_backpacks-1.16.4-1.11.6.87.jar             |Useful Backpacks              |usefulbackpacks               |1.11.6.87           |CREATE_REG|f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		torchmaster-2.3.6.jar                             |Torchmaster                   |torchmaster                   |2.3.6               |CREATE_REG|NOSIGNATURE
		resourcefulbees-1.16.5-0.5.10b.jar                |Resourceful Bees              |resourcefulbees               |1.16.5-0.5.10b      |ERROR     |NOSIGNATURE
		repurposed_structures-1.16.5-2.4.6.jar            |Repurposed Structures         |repurposed_structures         |1.16.5-2.4.6        |CREATE_REG|NOSIGNATURE
		theoneprobe-1.16-3.0.7.jar                        |The One Probe                 |theoneprobe                   |1.16-3.0.7          |CREATE_REG|NOSIGNATURE
		thermal_innovation-1.16.3-1.1.7.jar               |Thermal Innovation            |thermal_innovation            |1.1.7               |CREATE_REG|NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |CREATE_REG|NOSIGNATURE
		titanium-1.16.5-3.2.8.jar                         |Titanium                      |titanium                      |3.2.8               |CREATE_REG|NOSIGNATURE
		SilentLib-1.16.3-4.9.1+64.jar                     |Silent Lib                    |silentlib                     |4.9.1+64            |CREATE_REG|NOSIGNATURE
		BiomesOPlenty-1.16.4-13.0.0.431-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.431   |CREATE_REG|NOSIGNATURE
		MekanismAdditions-1.16.5-10.0.21.448.jar          |Mekanism: Additions           |mekanismadditions             |10.0.21             |CREATE_REG|NOSIGNATURE
		valkyrielib-1.16.5-3.0.7.2.jar                    |ValkyrieLib                   |valkyrielib                   |1.16.5-3.0.7.2      |CREATE_REG|NOSIGNATURE
		envirocore-1.16.5-3.0.7.1.jar                     |Environmental Core            |envirocore                    |1.16.5-3.0.7.1      |CREATE_REG|NOSIGNATURE
		envirotech-1.16.5-3.0.7.2.jar                     |Environmental Tech            |envirotech                    |3.0.7.2             |CREATE_REG|NOSIGNATURE
		enviromats-1.16.5-2.0.7.0.jar                     |Environmental Materials       |enviromats                    |2.0.7.0             |CREATE_REG|NOSIGNATURE
		pamhc2crops-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |CREATE_REG|NOSIGNATURE
		SilentGear-1.16.3-2.6.6+226.jar                   |Silent Gear                   |silentgear                    |2.6.6+226           |CREATE_REG|NOSIGNATURE
		Botania-1.16.4-411.jar                            |Botania                       |botania                       |1.16.4-411          |CREATE_REG|NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.1.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |CREATE_REG|NOSIGNATURE
		enviroenergy-1.16.5-3.0.7.0.jar                   |Environmental Energy          |enviroenergy                  |3.0.7.0             |CREATE_REG|NOSIGNATURE
		curios-forge-1.16.5-4.0.4.0.jar                   |Curios API                    |curios                        |1.16.5-4.0.4.0      |CREATE_REG|NOSIGNATURE
		Patchouli-1.16.4-50.jar                           |Patchouli                     |patchouli                     |1.16.4-50           |CREATE_REG|NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |CREATE_REG|NOSIGNATURE
		ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |CREATE_REG|NOSIGNATURE
		thermal_cultivation-1.16.3-1.1.6.jar              |Thermal Cultivation           |thermal_cultivation           |1.1.6               |CREATE_REG|NOSIGNATURE
		FastWorkbench-1.16.4-4.5.0.jar                    |FastWorkbench                 |fastbench                     |4.5.0               |CREATE_REG|NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |CREATE_REG|NOSIGNATURE
		StorageDrawers-1.16.3-8.2.2.jar                   |Storage Drawers               |storagedrawers                |8.2.2               |CREATE_REG|NOSIGNATURE
		thermal_expansion-1.16.3-1.1.6.jar                |Thermal Expansion             |thermal_expansion             |1.1.6               |CREATE_REG|NOSIGNATURE
		DrawersTooltip-1.16.2-2.1.0.jar                   |Drawers Tooltip               |drawerstooltip                |2.1.0               |CREATE_REG|NOSIGNATURE
		ftb-ultimine-1605.2.0-build.22-forge.jar          |FTB Ultimine                  |ftbultimine                   |1605.2.0-build.22   |CREATE_REG|NOSIGNATURE
		tombstone-1.16-6.3.2.jar                          |Corail Tombstone              |tombstone                     |1.16-6.3.2          |CREATE_REG|NOSIGNATURE
		Quark-r2.4-308.jar                                |Quark                         |quark                         |r2.4-308            |CREATE_REG|NOSIGNATURE
		MekanismTools-1.16.5-10.0.21.448.jar              |Mekanism: Tools               |mekanismtools                 |10.0.21             |CREATE_REG|NOSIGNATURE
		FastFurnace-1.16.4-4.4.0.jar                      |FastFurnace                   |fastfurnace                   |4.4.0               |CREATE_REG|NOSIGNATURE
		constructionwand-1.16.2-1.7.jar                   |Construction Wand             |constructionwand              |1.16.2-1.7          |CREATE_REG|NOSIGNATURE
		architectury-1.8.130-forge.jar                    |Architectury                  |architectury                  |1.8.130             |CREATE_REG|NOSIGNATURE
		ftb-gui-library-1605.2.1.40-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.40         |CREATE_REG|NOSIGNATURE
		ftb-teams-1604.1.0.15-forge.jar                   |FTB Teams                     |ftbteams                      |1604.1.0.15         |CREATE_REG|NOSIGNATURE
		ftb-chunks-1604.2.2.62.jar                        |FTB Chunks                    |ftbchunks                     |1604.2.2.62         |CREATE_REG|NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |CREATE_REG|NOSIGNATURE
		ferritecore-2.0.3-forge.jar                       |Ferrite Core                  |ferritecore                   |2.0.3               |CREATE_REG|41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		engineersdecor-1.16.4-1.1.8.jar                   |Engineer's Decor              |engineersdecor                |1.1.8               |CREATE_REG|bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |CREATE_REG|NOSIGNATURE
		cloth-config-4.11.14-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.14             |CREATE_REG|NOSIGNATURE
		allthetweaks-1.2.7-1.16.4-35.1.13.jar             |All The Tweaks                |allthetweaks                  |1.2.7-1.16.4-35.1.13|CREATE_REG|NOSIGNATURE
		kubejs-1605.3.6-build.171-forge.jar               |KubeJS                        |kubejs                        |1605.3.6-build.171  |CREATE_REG|NOSIGNATURE
		kubejs-mekanism-1604.1.1.6.jar                    |KubeJS Mekanism               |kubejs_mekanism               |1604.1.1.6          |CREATE_REG|NOSIGNATURE
		kubejs-thermal-1605.1.1.6.jar                     |KubeJS Thermal                |kubejs_thermal                |1605.1.1.6          |CREATE_REG|NOSIGNATURE
		u_team_core-1.16.4-3.1.17.192.jar                 |U Team Core                   |uteamcore                     |3.1.17.192          |CREATE_REG|f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		kubejs-create-1604.1.0.4.jar                      |KubeJS Create                 |kubejs_create                 |1604.1.0.4          |CREATE_REG|NOSIGNATURE
		trashcans-1.0.8-mc1.16.4.jar                      |Trash Cans                    |trashcans                     |1.0.8               |CREATE_REG|NOSIGNATURE
		byg-1.1.10.jar                                    |Oh The Biomes You'll Go       |byg                           |1.1.10              |CREATE_REG|NOSIGNATURE
		bwncr-1.16.4-3.9.16.jar                           |Bad Wither No Cookie Reloaded |bwncr                         |1.16.4-3.9.16       |CREATE_REG|NOSIGNATURE
		CobbleForDays-1.3.1.jar                           |Cobble For Days               |cobblefordays                 |1.3.1               |CREATE_REG|NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |CREATE_REG|NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v1b.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v1b          |CREATE_REG|5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		geckolib-forge-1.16.5-3.0.14.jar                  |GeckoLib                      |geckolib3                     |3.0.14              |CREATE_REG|NOSIGNATURE
		ars_nouveau-1.16.4-1.11.5.jar                     |Ars Nouveau                   |ars_nouveau                   |1.11.5              |CREATE_REG|NOSIGNATURE
	Crash Report UUID: 5836d4c0-8ebe-4456-817b-50f2e9805ecb

**Comment by MadWomen** [comment]
something to do with resourceful bees, try to remove everything and try to reinstall the server and see if that works.

**Comment by kaancl3344** [comment]
i already tried fresh installing twice. When i remove bee mod it works fine.
