### ISSUE TITLE
Cant create an online server with a raspberry pi 4

### ISSUE THREAD

**Issue by Mageh533** [AllTheMods/SLOP2-slice-of-pie-2#8]
I have been trying to run a server using my raspberry pi 4 (4GB). However although it successfully opens i can connect to it, my online friends cant. My ports are open and i can perfectly fine create a server using my normal PC or with a laptop but i cant do it with my pi 4. I tried forcing an ipv4 address using -Djava.net.preferIPv4Stack=true in the launch options but no luck. I am using Ubuntu 64 bits as recommended.

**Comment by MadWomen** [comment]
have they added the port and the end of the ip? example: "x.x.x.x:25565"
